name = "Advanced Generators"
filename = "generators-0.9.20.12-mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2516/219/generators-0.9.20.12-mc1.12.2.jar"
hash-format = "sha1"
hash = "f4914a0231adeca5d1cab5569a5803ed20e5806a"

[update]
[update.curseforge]
file-id = 2516219
project-id = 223622
