name = "AI Improvements"
filename = "AIImprovements-1.12-0.0.1b3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2450/734/AIImprovements-1.12-0.0.1b3.jar"
hash-format = "sha1"
hash = "ef4b64cd4fc10522ead1f659b81e471af455c3fe"

[update]
[update.curseforge]
file-id = 2450734
project-id = 233019
