name = "Ancient Warfare 2"
filename = "ancientwarfare-1.12.2-2.7.0.1038.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3293/318/ancientwarfare-1.12.2-2.7.0.1038.jar"
hash-format = "murmur2"
hash = "65374617"

[update]
[update.curseforge]
file-id = 3293318
project-id = 224602
