name = "ArchitectureCraft - TridentMC Version"
filename = "architecturecraft-1.12-3.98.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2750/633/architecturecraft-1.12-3.98.jar"
hash-format = "sha1"
hash = "b84097e2f7d76904333c872edeaa7749d6e10279"

[update]
[update.curseforge]
file-id = 2750633
project-id = 277631
