name = "Armor Toughness Bar"
filename = "toughnessbar-2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2851/670/toughnessbar-2.4.jar"
hash-format = "sha1"
hash = "a13eb8b797cec70dd07201fe5eb4b606ff7372e0"

[update]
[update.curseforge]
file-id = 2851670
project-id = 313816
