name = "AutoRegLib"
filename = "AutoRegLib-1.3-32.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2746/11/AutoRegLib-1.3-32.jar"
hash-format = "sha1"
hash = "267269ca7f1a71fb3bb35bdb8e61702a4da6263e"

[update]
[update.curseforge]
file-id = 2746011
project-id = 250363
