name = "Bad Wither No Cookie - Reloaded"
filename = "badwithernocookiereloaded-1.12.2-3.4.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3045/651/badwithernocookiereloaded-1.12.2-3.4.18.jar"
hash-format = "sha1"
hash = "11ab53b71d86a7da97e5fa1a1705b62aa8da2b9c"

[update]
[update.curseforge]
file-id = 3045651
project-id = 261251
