name = "Better Questing"
filename = "BetterQuesting-3.5.329.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2950/248/BetterQuesting-3.5.329.jar"
hash-format = "sha1"
hash = "45b1b20dfbd79c64f226625076f228e4efec4586"

[update]
[update.curseforge]
file-id = 2950248
project-id = 238856
