name = "Better Questing - Quest Book"
filename = "questbook-3.1.1-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2539/562/questbook-3.1.1-1.12.jar"
hash-format = "sha1"
hash = "9a9c9c3734f775fce2839dc3deb06f3a7ab64471"

[update]
[update.curseforge]
file-id = 2539562
project-id = 242106
