name = "Biomes O' Plenty"
filename = "BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2842/510/BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar"
hash-format = "sha1"
hash = "6f281febea0746d2229f692cb719bd017ec70b32"

[update]
[update.curseforge]
file-id = 2842510
project-id = 220318
