name = "Bookshelf"
filename = "Bookshelf-1.12.2-2.3.590.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2836/960/Bookshelf-1.12.2-2.3.590.jar"
hash-format = "sha1"
hash = "83a1864dd78f48102609849dd36866d6cf32b907"

[update]
[update.curseforge]
file-id = 2836960
project-id = 228525
