name = "Chisel"
filename = "Chisel-MC1.12.2-1.0.2.45.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2915/375/Chisel-MC1.12.2-1.0.2.45.jar"
hash-format = "sha1"
hash = "d378cee9195841ea78bb9800f543d718ef2c60ef"

[update]
[update.curseforge]
file-id = 2915375
project-id = 235279
