name = "Chunk-Pregenerator"
filename = "Chunk Pregenerator-V1.12-2.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3214/752/Chunk%20Pregenerator-V1.12-2.5.0.jar"
hash-format = "sha1"
hash = "a6b7168e190aa9a8f665d826fa9cd77aba419135"

[update]
[update.curseforge]
file-id = 3214752
project-id = 267193
