name = "Common Capabilities"
filename = "CommonCapabilities-1.12.2-2.4.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3053/17/CommonCapabilities-1.12.2-2.4.8.jar"
hash-format = "sha1"
hash = "1f9554d8595d7833f983e5dcd973081bdd725825"

[update]
[update.curseforge]
file-id = 3053017
project-id = 247007
