name = "Construct's Armory"
filename = "conarm-1.12.2-1.2.5.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3174/535/conarm-1.12.2-1.2.5.10.jar"
hash-format = "sha1"
hash = "373e8f6f56605d7eacb5d7d2f4e1ffea5e6d844b"

[update]
[update.curseforge]
file-id = 3174535
project-id = 287683
