name = "Controlling"
filename = "Controlling-3.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3025/548/Controlling-3.0.10.jar"
hash-format = "sha1"
hash = "151671af56599d39ef5ca41bf9bda3584b6818e1"

[update]
[update.curseforge]
file-id = 3025548
project-id = 250398
