name = "CraftStudio API"
filename = "CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2661/859/CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar"
hash-format = "sha1"
hash = "868d96028427e39495f441e43e60a9b77225b5ad"

[update]
[update.curseforge]
file-id = 2661859
project-id = 268704
