name = "CraftTweaker"
filename = "CraftTweaker2-1.12-4.1.20.625.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3223/511/CraftTweaker2-1.12-4.1.20.625.jar"
hash-format = "sha1"
hash = "c436a0f32ba698460f56e379d137894445e945f7"

[update]
[update.curseforge]
file-id = 3223511
project-id = 239197
