name = "Cyclic"
filename = "Cyclic-1.12.2-1.20.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3279/606/Cyclic-1.12.2-1.20.9.jar"
hash-format = "sha1"
hash = "d7d6f6931a5998175f2c3d1a75e136c74051f53a"

[update]
[update.curseforge]
file-id = 3279606
project-id = 239286
