name = "/dank/null"
filename = "DankNull-1.12.2-1.7.91.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2920/596/DankNull-1.12.2-1.7.91.jar"
hash-format = "sha1"
hash = "4db0be5d1557d2c6754579177c0cab361462304b"

[update]
[update.curseforge]
file-id = 2920596
project-id = 272514
