name = "Dark Utilities"
filename = "DarkUtils-1.12.2-1.8.230.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2813/586/DarkUtils-1.12.2-1.8.230.jar"
hash-format = "sha1"
hash = "3f34c35903ca09e637dc3426eb81ca64ced0429a"

[update]
[update.curseforge]
file-id = 2813586
project-id = 242195
