name = "Diet Hoppers"
filename = "diethopper-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2482/543/diethopper-1.1.jar"
hash-format = "sha1"
hash = "2aea3d9a64551cefe0a1b6f5c5edf57959796b66"

[update]
[update.curseforge]
file-id = 2482543
project-id = 278385
