name = "DiscordSuite"
filename = "DiscordSuite-2.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2577/684/DiscordSuite-2.2.4.jar"
hash-format = "sha1"
hash = "cdf2f55177e86a1c14ce80dbee2aeba47e88285a"

[update]
[update.curseforge]
file-id = 2577684
project-id = 282743
