name = "Embers Rekindled"
filename = "EmbersRekindled-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3225/431/EmbersRekindled-1.18.jar"
hash-format = "sha1"
hash = "36fdc16c78629d7d7b36cfc357c224ed10044431"

[update]
[update.curseforge]
file-id = 3225431
project-id = 300777
