name = "Ender IO"
filename = "EnderIO-1.12.2-5.3.70.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3328/811/EnderIO-1.12.2-5.3.70.jar"
hash-format = "sha1"
hash = "55e25a5332c3dc5898f6a08a971dc21990c8eb96"

[update]
[update.curseforge]
file-id = 3328811
project-id = 64578
