name = "Environmental Materials"
filename = "environmentalmaterials-1.12.2-1.0.20.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2691/535/environmentalmaterials-1.12.2-1.0.20.1.jar"
hash-format = "sha1"
hash = "e9d9530a520dc3fe3ef112e297a1147cbaecca68"

[update]
[update.curseforge]
file-id = 2691535
project-id = 278825
