name = "Extra Bit Manipulation"
filename = "ExtraBitManipulation-1.12.2-3.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2630/81/ExtraBitManipulation-1.12.2-3.4.1.jar"
hash-format = "sha1"
hash = "b6b018634075e995bdaf1318a4ac7d0f6c1d2158"

[update]
[update.curseforge]
file-id = 2630081
project-id = 240959
