name = "Farming for Blockheads"
filename = "FarmingForBlockheads_1.12.2-3.1.28.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2733/508/FarmingForBlockheads_1.12.2-3.1.28.jar"
hash-format = "sha1"
hash = "59b2ad2017daaab5b73f2c6851a06b898bcb049b"

[update]
[update.curseforge]
file-id = 2733508
project-id = 261924
