name = "FastWorkbench"
filename = "FastWorkbench-1.12.2-1.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2838/777/FastWorkbench-1.12.2-1.7.3.jar"
hash-format = "sha1"
hash = "e40e850c8fb065e805538c8bf275d64b6cd5d6a7"

[update]
[update.curseforge]
file-id = 2838777
project-id = 288885
