name = "Fence Jumper"
filename = "fencejumper-1.12-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2591/87/fencejumper-1.12-1.0.5.jar"
hash-format = "sha1"
hash = "e6f23c18081d59deb55a625e1291b9fe9c1157de"

[update]
[update.curseforge]
file-id = 2591087
project-id = 254652
