name = "Flat Colored Blocks"
filename = "flatcoloredblocks-mc1.12-6.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2715/827/flatcoloredblocks-mc1.12-6.8.jar"
hash-format = "sha1"
hash = "0b6ae9ad1b622a65f988c887b34f7d64a5e2562a"

[update]
[update.curseforge]
file-id = 2715827
project-id = 238590
