name = "Backpacks"
filename = "backpack-3.0.2-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2554/237/backpack-3.0.2-1.12.2.jar"
hash-format = "sha1"
hash = "081807b00c859d209aafda8622f2126316d10c25"

[update]
[update.curseforge]
file-id = 2554237
project-id = 59143
