name = "Immersive Engineering"
filename = "ImmersiveEngineering-0.12-98.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2974/106/ImmersiveEngineering-0.12-98.jar"
hash-format = "sha1"
hash = "633070d9c447fdaf6a9ead59425017815c890c63"

[update]
[update.curseforge]
file-id = 2974106
project-id = 231951
