name = "Integration Foregoing"
filename = "IntegrationForegoing-1.12.2-1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3200/529/IntegrationForegoing-1.12.2-1.11.jar"
hash-format = "sha1"
hash = "1a6f3f87cdbce8e3c93da2de10854cc853ddc9f0"

[update]
[update.curseforge]
file-id = 3200529
project-id = 277938
