name = "Inventory Tweaks [1.12 only] "
filename = "InventoryTweaks-1.64+dev.151.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2923/460/InventoryTweaks-1.64+dev.151.jar"
hash-format = "sha1"
hash = "3ba1e59a5109f3e94a4a0170877006b72fa77b1e"

[update]
[update.curseforge]
file-id = 2923460
project-id = 223094
