name = "IvToolkit"
filename = "IvToolkit-1.3.3-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2443/253/IvToolkit-1.3.3-1.12.jar"
hash-format = "sha1"
hash = "522e60b48721b558f6dea1fdfa2b235162366649"

[update]
[update.curseforge]
file-id = 2443253
project-id = 224535
