name = "Just Sleep"
filename = "JustSleep-1.0.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2640/24/JustSleep-1.0.0.1.jar"
hash-format = "sha1"
hash = "b360418b40558baa8bc3a3850f3f3226a4876c84"

[update]
[update.curseforge]
file-id = 2640024
project-id = 307416
