name = "Just Enough HarvestCraft (JEHC)"
filename = "just-enough-harvestcraft-1.12.2-1.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2997/129/just-enough-harvestcraft-1.12.2-1.7.2.jar"
hash-format = "sha1"
hash = "4ba48aff5c8936e60939c16faebfd5576b4d8770"

[update]
[update.curseforge]
file-id = 2997129
project-id = 267939
