name = "LibrarianLib"
filename = "librarianlib-1.12.2-4.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3041/340/librarianlib-1.12.2-4.22.jar"
hash-format = "sha1"
hash = "f2e75d6899a26fe32b0b0ee2ad33c68a70bd91e6"

[update]
[update.curseforge]
file-id = 3041340
project-id = 252910
