name = "Magic Bees"
filename = "MagicBees-1.12.2-3.2.25.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2855/61/MagicBees-1.12.2-3.2.25.jar"
hash-format = "sha1"
hash = "5a396effc70fe30bc8091e9c151d4feec5f62eff"

[update]
[update.curseforge]
file-id = 2855061
project-id = 65764
