name = "MalisisCore"
filename = "malisiscore-1.12.2-6.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2680/892/malisiscore-1.12.2-6.5.1.jar"
hash-format = "sha1"
hash = "4b4a9fd82030ec2e31e64c9807779695323800c3"

[update]
[update.curseforge]
file-id = 2680892
project-id = 223896
