name = "MCMultiPart"
filename = "MCMultiPart-2.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2615/930/MCMultiPart-2.5.3.jar"
hash-format = "sha1"
hash = "b32fb5efb99dedf207d3623e222ea67e20655fcc"

[update]
[update.curseforge]
file-id = 2615930
project-id = 239431
