name = "MeeCreeps"
filename = "meecreeps-1.12-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2707/393/meecreeps-1.12-1.3.1.jar"
hash-format = "sha1"
hash = "5aafccc08f4f0543d83533d5c73b1512a8d71b20"

[update]
[update.curseforge]
file-id = 2707393
project-id = 281390
