name = "MemoryTester"
filename = "MemoryTester-0.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2683/370/MemoryTester-0.4.2.jar"
hash-format = "sha1"
hash = "1f37067815ab2be1d9d0c3b443c5dc403ed67d4d"

[update]
[update.curseforge]
file-id = 2683370
project-id = 295736
