name = "ModTweaker"
filename = "modtweaker-4.0.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2881/277/modtweaker-4.0.18.jar"
hash-format = "sha1"
hash = "919614e5f1591d79c81b563a42042cfacccb42c1"

[update]
[update.curseforge]
file-id = 2881277
project-id = 220954
