name = "More Overlays"
filename = "moreoverlays-1.15.1-mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/657/moreoverlays-1.15.1-mc1.12.2.jar"
hash-format = "sha1"
hash = "b308fe363f23343d0b073d04883c5fca63b08d0b"

[update]
[update.curseforge]
file-id = 2745657
project-id = 243478
