name = "Morph-o-Tool"
filename = "Morph-o-Tool-1.2-21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2658/176/Morph-o-Tool-1.2-21.jar"
hash-format = "sha1"
hash = "55a363ccd8e0614229991cd1f6bf831eaf874ff7"

[update]
[update.curseforge]
file-id = 2658176
project-id = 245287
