name = "Mouse Tweaks"
filename = "MouseTweaks-2.10.1-mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3359/843/MouseTweaks-2.10.1-mc1.12.2.jar"
hash-format = "sha1"
hash = "17f778c7e64f1b71cee4e1f64d35a749bb6ea93d"

[update]
[update.curseforge]
file-id = 3359843
project-id = 60089
