name = "MTLib"
filename = "MTLib-3.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2684/561/MTLib-3.0.6.jar"
hash-format = "sha1"
hash = "a4625a61c9ef53412e0e467d23f25c5543658677"

[update]
[update.curseforge]
file-id = 2684561
project-id = 253211
