name = "Neat"
filename = "Neat 1.4-17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2595/310/Neat%201.4-17.jar"
hash-format = "sha1"
hash = "831c286d99fe78503e966ef80ad27f54ae6a81cb"

[update]
[update.curseforge]
file-id = 2595310
project-id = 238372
