name = "No Night Vision Flashing"
filename = "NoNVFlash-1.12.2-1.2.0.3-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2550/651/NoNVFlash-1.12.2-1.2.0.3-universal.jar"
hash-format = "sha1"
hash = "2c52f878f12898385cb61d3e192bf174697408d9"

[update]
[update.curseforge]
file-id = 2550651
project-id = 291926
