name = "OldJavaWarning"
filename = "OldJavaWarning-1.12.2-1.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2867/50/OldJavaWarning-1.12.2-1.1.11.jar"
hash-format = "sha1"
hash = "a197d88223f05973c87e11c0eb33f6586609240e"

[update]
[update.curseforge]
file-id = 2867050
project-id = 293496
