name = "Ore Excavation"
filename = "OreExcavation-1.4.150.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2897/369/OreExcavation-1.4.150.jar"
hash-format = "sha1"
hash = "d5e32554a78d95e40ecb85c32138531cb433f19f"

[update]
[update.curseforge]
file-id = 2897369
project-id = 250898
