name = "Pam's HarvestCraft"
filename = "Pam's HarvestCraft 1.12.2zg.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2904/825/Pam%27s%20HarvestCraft%201.12.2zg.jar"
hash-format = "sha1"
hash = "a064b434253305424755943dd66f389855ade953"

[update]
[update.curseforge]
file-id = 2904825
project-id = 221857
