name = "Phosphor (Forge)"
filename = "phosphor-1.12.2-0.2.6+build50-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2747/710/phosphor-1.12.2-0.2.6+build50-universal.jar"
hash-format = "sha1"
hash = "d4781f46fb18f0c6ed03893465244e7ec7dc8b8c"

[update]
[update.curseforge]
file-id = 2747710
project-id = 318255
