name = "PlayersDropHeads"
filename = "playersdropheads-1.12.x-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2529/710/playersdropheads-1.12.x-1.1.0.jar"
hash-format = "sha1"
hash = "ac10c7d93be10b0ed70bd0d4b75cb669b34e8f7b"

[update]
[update.curseforge]
file-id = 2529710
project-id = 286953
