name = "Quark"
filename = "Quark-r1.6-179.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2924/91/Quark-r1.6-179.jar"
hash-format = "sha1"
hash = "35521fd8911b6ef893afbfe7d0d5d04962b3360d"

[update]
[update.curseforge]
file-id = 2924091
project-id = 243121
