name = "Recurrent Complex"
filename = "RecurrentComplex-1.4.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2689/602/RecurrentComplex-1.4.8.2.jar"
hash-format = "sha1"
hash = "b9dff4716409bd622b4fc160f2446a124da5c3a2"

[update]
[update.curseforge]
file-id = 2689602
project-id = 223150
