name = "Rustic"
filename = "rustic-1.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3107/974/rustic-1.1.7.jar"
hash-format = "sha1"
hash = "567832a6b073e59fa29f2f694e224008707db2f8"

[update]
[update.curseforge]
file-id = 3107974
project-id = 256141
