name = "Scannable"
filename = "Scannable-MC1.12.2-1.6.3.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3146/549/Scannable-MC1.12.2-1.6.3.26.jar"
hash-format = "sha1"
hash = "b949f46eef7fe63e42e4d5a618f1e26e66a1af5c"

[update]
[update.curseforge]
file-id = 3146549
project-id = 266784
