name = "Schematica"
filename = "Schematica-1.12.2-1.8.0.169-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2554/100/Schematica-1.12.2-1.8.0.169-universal.jar"
hash-format = "sha1"
hash = "cc8c851bc47ecf314c3974e3b90acfa1a62105ac"

[update]
[update.curseforge]
file-id = 2554100
project-id = 225603
