name = "Spice of Life: Carrot Edition"
filename = "solcarrot-1.12.2-1.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2959/847/solcarrot-1.12.2-1.8.4.jar"
hash-format = "sha1"
hash = "3197a040e5a090ea12a2e2095a8cca0e6f650c13"

[update]
[update.curseforge]
file-id = 2959847
project-id = 277616
