name = "Streams"
filename = "Streams-1.12-0.4.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3109/315/Streams-1.12-0.4.9.jar"
hash-format = "sha1"
hash = "82408b7604a56f06fbb25f23e9aef2ea154e17c2"

[update]
[update.curseforge]
file-id = 3109315
project-id = 229769
