name = "Thaumic Tinkerer"
filename = "thaumictinkerer-1.12.2-5.0-620a0c5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2957/213/thaumictinkerer-1.12.2-5.0-620a0c5.jar"
hash-format = "sha1"
hash = "a1aa3c6d895539c2d4cb8413ac1f54dddb4aff0f"

[update]
[update.curseforge]
file-id = 2957213
project-id = 75598
