name = "Toast Control"
filename = "Toast Control-1.12.2-1.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2707/353/Toast%20Control-1.12.2-1.8.1.jar"
hash-format = "sha1"
hash = "7365b5415d5f1a39997fe142ccc42ae732e31c01"

[update]
[update.curseforge]
file-id = 2707353
project-id = 271740
