name = "Tomb Many Graves 2"
filename = "TombManyGraves-1.12-4.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2619/249/TombManyGraves-1.12-4.2.0.jar"
hash-format = "sha1"
hash = "cfba896b87294e2351c383b5d4127112d26ab5e0"

[update]
[update.curseforge]
file-id = 2619249
project-id = 262823
