name = "Unloader"
filename = "unloader-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2572/528/unloader-1.2.0.jar"
hash-format = "sha1"
hash = "6c615f6bd2dcd9ad30cb69422fd3241ee6f45816"

[update]
[update.curseforge]
file-id = 2572528
project-id = 286230
