name = "Villager Market"
filename = "villager-market-1.12.2-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2882/805/villager-market-1.12.2-1.0.2.jar"
hash-format = "sha1"
hash = "69a0ad30e4accf20cadd4c8c9e52aaacc7c2840b"

[update]
[update.curseforge]
file-id = 2882805
project-id = 261505
