name = "WanionLib"
filename = "WanionLib-1.12.2-2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2651/482/WanionLib-1.12.2-2.2.jar"
hash-format = "sha1"
hash = "bbee84cafbbc72b24ee987fda668b3ee48ced74a"

[update]
[update.curseforge]
file-id = 2651482
project-id = 253043
