name = "Wawla - What Are We Looking At"
filename = "Wawla-1.12.2-2.6.275.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2916/368/Wawla-1.12.2-2.6.275.jar"
hash-format = "sha1"
hash = "783157c607149875de1e045d72382d370256257c"

[update]
[update.curseforge]
file-id = 2916368
project-id = 224712
