name = "WrapUp"
filename = "WrapUp-1.12-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2486/198/WrapUp-1.12-1.1.3.jar"
hash-format = "sha1"
hash = "29f89705011794531150e5e00a73d62cc0134888"

[update]
[update.curseforge]
file-id = 2486198
project-id = 275153
