name = "XNet"
filename = "xnet-1.12-1.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/852/xnet-1.12-1.8.2.jar"
hash-format = "sha1"
hash = "085f5aef1d407f815028e5ecc87265cc5d8142e6"

[update]
[update.curseforge]
file-id = 2745852
project-id = 260912
