name = "YNot"
filename = "YNot-0.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2708/30/YNot-0.2.4.jar"
hash-format = "sha1"
hash = "7192f98116899b6755fbd631bff2721c40f65bea"

[update]
[update.curseforge]
file-id = 2708030
project-id = 283589
