name = "ZeroCore 2"
filename = "zerocore-1.12-0.1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2648/891/zerocore-1.12-0.1.2.3.jar"
hash-format = "sha1"
hash = "e9bdf05511cf81a5f6e3d4ad3ab80442a1910cfa"

[update]
[update.curseforge]
file-id = 2648891
project-id = 247921
